name: Help Request
description: File a help request for SR2 Planner.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["SR2Planner/1"]
assignees:
  - SR2Planner
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this help request for SR2 Planner!
  - type: dropdown
    id: version
    attributes:
      label: Type
      description: What type of help request is this?
      options:
        - Feature Request
        - Bug Report
        - Question
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What is your request about?
      placeholder: Describe what your request is about
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using for SR2 Planner?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
