name: Help Request
description: File a help request for SR2 Planner.
title: "Help Request: "
labels: ["new"]
projects: ["SR2Planner/1"]
assignees:
  - SR2Planner
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this help request for SR2 Planner!
  - type: dropdown
    id: version
    attributes:
      label: Type
      description: What type of help request is this?
      options:
        - Feature Request
        - Bug Report
        - Question
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What is your request about?
      placeholder: Describe what your request is about
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using for SR2 Planner?
      description: In case of a bug report, please select the browsers where you are observing the bug.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mobile
    validations:
      required: false
